version: "3.7"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data/config:/var/lib/grafana
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus.yml
    volumes:
      - ./prometheus/data/prometheus.yml:/etc/prometheus.yml
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    ports:
      - 9221:9221
    volumes:
      - ./prometheus-pve-exporter/data/pve.yml:/etc/pve.yml
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    # SUS!
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"