version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/config:/data
    logging:
     options:
       max-size: 25m
       max-file: "1"
    security_opt:
      - apparmor:unconfined