x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: loki
    options:
      loki-url: "http://host-or-ip:3100/loki/api/v1/push"

services:
  cadvisor:
    <<: *defaults
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-synology
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /volume1/@docker:/var/lib/docker:ro
      - /dev/vg1:/dev/disk:ro
    ports:
      - "8888:8080"
    privileged: true
    devices:
      - /dev/kmsg
  minio:
    <<: *defaults
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    networks:
      - docker
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${NPM_DB_PASSWORD}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/S3/:/data:rw
      - ${DOCKERCONFDIR}:/root/.minio:rw
  node-exporter:
    <<: *defaults
    privileged: true
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
  sabnzbd:
    <<: *defaults
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sabnzbd:/config:rw
      - ${DOCKERSTORAGEDIR}/usenet:${STORAGE_ROOT}/usenet:rw
    networks:
      - docker
  transmission-openvpn:
    <<: *defaults
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmission:/config:rw
      - ${DOCKERSTORAGEDIR}/torrents:${STORAGE_ROOT}/torrents:rw
    dns:
      - 1.1.1.1
      - 8.8.8.8
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=netherlands
      - OPENVPN_USERNAME=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LAN_NETWORK}
      - TRANSMISSION_WEB_UI=kettu
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=${STORAGE_ROOT}/torrents/completed
      - TRANSMISSION_INCOMPLETE_DIR=${STORAGE_ROOT}/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=${STORAGE_ROOT}/torrents/watch
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    ports:
      - '9091:9091'
    networks:
      - docker
networks:
  docker:
    driver: bridge
    name: docker