version: "3.7"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data/config:/var/lib/grafana
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus.yml
    volumes:
      - ./prometheus/data/prometheus.yml:/etc/prometheus.yml
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    ports:
      - 9221:9221
    volumes:
      - ./prometheus-pve-exporter/data/pve.yml:/etc/pve.yml
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus-pve-exporter.entrypoints=http"
      - "traefik.http.routers.prometheus-pve-exporter.rule=Host(`prometheus-pve-exporter.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.prometheus-pve-exporter-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus-pve-exporter.middlewares=prometheus-pve-exporter-https-redirect"
      - "traefik.http.routers.prometheus-pve-exporter-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-pve-exporter-secure.rule=Host(`prometheus-pve-exporter.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.prometheus-pve-exporter-secure.tls=true"
      - "traefik.http.routers.prometheus-pve-exporter-secure.service=prometheus-pve-exporter"
      - "traefik.http.services.prometheus-pve-exporter.loadbalancer.server.port=9221"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
    # SUS!
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=http"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect"
      - "traefik.http.routers.cadvisor-secure.entrypoints=https"
      - "traefik.http.routers.cadvisor-secure.rule=Host(`cadvisor.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.cadvisor-secure.tls=true"
      - "traefik.http.routers.cadvisor-secure.service=cadvisor"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
 proxy:
   external: true
