version: "3.7"

services:
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    volumes:
        - ./pia/data/config:/pia
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    ports:
        - 8888:8888/tcp
        - 8388:8388/tcp
        - 8388:8388/udp
        - 9091:9091 # Transmission
        - 7878:7878 # Radarr
        - 8989:8989 # Sonarr
        - 9117:9117 # Jackett
    environment:
        - LOCAL_NETWORK={{ SUBNET }}
        - LOC=ca_ontario
        - USER={{ PIA_USER }}
        - PASS={{ PIA_PASS }}
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
        - VPNDNS={{ DNS_SERVER }}
        - PORT_FORWARDING=1
        - PORT_FILE/pia/port.dat
        - PORT_PERSIST=1
    sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 30s
        timeout: 10s
        retries: 3
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission.rule=Host(`transmission.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.transmission-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.transmission.middlewares=transmission-https-redirect"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.rule=Host(`transmission.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.routers.jackett.rule=Host(`jackett.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.jackett-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jackett.middlewares=jackett-https-redirect"
      - "traefik.http.routers.jackett-secure.entrypoints=https"
      - "traefik.http.routers.jackett-secure.rule=Host(`jackett.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.jackett-secure.tls=true"
      - "traefik.http.routers.jackett-secure.service=jackett"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.{{ DOMAIN_NAME }}`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.{{ DOMAIN_NAME }}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TRANSMISSION_WEB_HOME=/kettu/
    volumes:
      - ./transmission/data/config:/config
      - {{ STORAGE_PATH }}/downloads:/downloads
      - {{ STORAGE_PATH }}/downloads/watch:/watch
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./jackett/data/config:/config
      - {{ STORAGE_PATH }}/downloads:/downloads
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./sonarr/data/config:/config
      - {{ STORAGE_PATH }}/tv:/tv
      - {{ STORAGE_PATH }}/downloads:/downloads
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./radarr/data/config:/config
      - {{ STORAGE_PATH }}/movie:/movies
      - {{ STORAGE_PATH }}/downloads:/downloads
    restart: unless-stopped
    logging:
     options:
       max-size: 25m
       max-file: "1"
networks:
 proxy:
   external: true
