version: "3.7"

services:
  organizr:
    image: linuxserver/organizr:latest
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
     - ./data/config:/config
    ports:
     - 9983:80
    security_opt:
     - apparmor:unconfined
    restart: unless-stopped
    logging:
      options:
        max-size: 25m
        max-file: "1"