version: "3.7"

services:
  openvpn-as:
    image: linuxserver/openvpn-as:latest
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - INTERFACE=eth0
    volumes:
      - data/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    network_mode: bridge
    logging:
     options:
       max-size: 25m
       max-file: "1"
       